### ISSUE TITLE
Multiple stamps per region

### ISSUE THREAD

**Issue by DavidDury** [Azure/Mission-Critical-Connected#550] opened 2023-05-10 10:22 UTC
In README here: https://github.com/Azure/Mission-Critical-Connected/blob/main/src/infra/README.md is stated:

**Stamp resources
A stamp is a regional deployment and can also be considered as a scale-unit. For now we only always deploy one stamp in an Azure Region but this can be extended to allow multiple stamps per region if required.**

I am very new to terraform how can this be achieved? So basically deploy for example two stamps per region each stamp in different availability zone, having a total of four stamps: 2 per region and in each region 1 stamp in one AZ and 1 stamp in other AZ.

**Comment by sebader** [comment] 2023-06-05 10:53
Duplicate of https://github.com/Azure/Mission-Critical-Online/issues/958

**Closed by sebader** 2023-06-05 10:53 UTC
